#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f toplevel.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace toplevel.sv program_counter/pc_module.sv program_counter/pc_reg.sv data/data_top_level.sv data/register_file.sv data/alu_src_mux.sv data/alu.sv control/control_unit.sv control/instruction_memory.sv control/extend.sv --exe toplevel_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtoplevel.mk Vtoplevel

# run executable simulation file 
obj_dir/Vtoplevel