#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f toplevel.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace toplevel.sv Role1/pc_module.sv Role1/pc_reg.sv Role2/role2toplevel.sv Role2/regfile.sv Role2/multiplexer.sv Role2/alu.sv Role3/controlunit.sv Role3/instrmem.sv Role3/signextend.sv --exe toplevel_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtoplevel.mk Vtoplevel

# run executable simulation file 
obj_dir/Vtoplevel