#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f fetch_decode_top.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace fetch_decode_top.sv --exe fetch_decode_test_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vfetch_decode_top.mk Vfetch_decode_top

# run executable simulation file 
obj_dir/Vfetch_decode_top