#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top_level.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace top_level.sv --exe top_level_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_level.mk Vtop_level

# run executable simulation file 
obj_dir/Vtop_level