#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f PCSrclogic_test.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace PCSrclogic_test.sv --exe pc_src_logic_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPCSrclogic_test.mk VPCSrclogic_test

# run executable simulation file 
obj_dir/VPCSrclogic_test