#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f execute.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace execute.sv --exe execute_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vexecute.mk Vexecute

# run executable simulation file 
obj_dir/Vexecute