#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f test_register.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace test_register.sv --exe test_register_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtest_register.mk Vtest_register

# run executable simulation file 
obj_dir/Vtest_register