#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f extend.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace extend.sv --exe extend_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vextend.mk Vextend

# run executable simulation file 
obj_dir/Vextend