#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f cache.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace cache.sv --exe cache_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcache.mk Vcache

# run executable simulation file 
obj_dir/Vcache