#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f combined.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace combined.sv --exe combined_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcombined.mk Vcombined

# run executable simulation file 
obj_dir/Vcombined